### ISSUE TITLE
How do I use this decryptor in the radar?

### ISSUE THREAD

**Issue by liuguanxiong** [nmodnation/pubg_decryptor#2]
Anyone help? I want to try if I can put this decryptor in proper location of vmradar project and maybe do some development. Thanks.

**Comment by furioussoul** [comment]
Possibly it read memory from base ref  on pc you play pubg,

**Comment by liuguanxiong** [comment]
I do not think we need to read anything from memory. It seems like setting the decryption on the 2nd pc is sufficient

**Comment by whtiehack** [comment]
it's used in the  pugb_map_hack

**Comment by liuguanxiong** [comment]
Thank you so much
