### ISSUE TITLE
anyone tell me how to use it

### ISSUE THREAD

**Issue by furioussoul** [nmodnation/pubg_decryptor#3]

**Comment by heliojuniorkroger** [comment]
+1

**Comment by heliojuniorkroger** [comment]
This package is written in C, but the radar is written in Kotlin. Sad.

**Comment by furioussoul** [comment]
i dont think it can run on radar cause it reads memory

**Comment by furioussoul** [comment]
radar just sniffs package

**Comment by tobyxdd** [comment]
The README should be good enough for you if you really understand what you're doing here and what this is about. Just replace the RPM/WPM stubs with your implementation and it's good to go.

Also please stop asking about radar bullshits, this project is for external cheats not packet-based radars.

**Comment by tobyxdd** [comment]
老哥是同城的人？

**Comment by GeT1t** [comment]
大家加个好友交流下？

**Comment by xuboweiqqqq** [comment]
交流解密的加我好友 Q78807100

**Comment by furioussoul** [comment]
1
